#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use MadMikeyB\SonosBot\Command\ExampleCommand;
use MadMikeyB\SonosBot\Command\SonosCommand;
use MadMikeyB\SonosBot\Command\SonosCrossFadeCommand;
use MadMikeyB\SonosBot\Command\SonosInfoCommand;
use MadMikeyB\SonosBot\Command\SonosPauseCommand;
use MadMikeyB\SonosBot\Command\SonosPlayCommand;
use MadMikeyB\SonosBot\Command\SonosPlaylistsCommand;
use MadMikeyB\SonosBot\Command\SonosRepeatCommand;
use MadMikeyB\SonosBot\Command\SonosShuffleCommand;
use Symfony\Component\Console\Application;

$commands = [
    new ExampleCommand,
    new SonosCommand,
    new SonosPlayCommand,
    new SonosPauseCommand,
    new SonosRepeatCommand,
    new SonosShuffleCommand,
    new SonosCrossFadeCommand,
    new SonosInfoCommand,
    new SonosPlaylistsCommand
];

$application = new Application('Sonos Slackbot', '0.0.1');

foreach ($commands as $command) {
    $application->add($command);
}

$application->run();
